@Host=http://localhost:4002

### Create task
POST {{Host}}/tasks
Content-Type: application/json

{
    "title": "Wash the car"
}

### Complete task
POST {{Host}}/tasks/fcdc88eb-c19d-4b6d-8833-065ab12baef3/complete