@Host=http://localhost:4000

### Create task
POST {{Host}}/eventstore
Content-Type: application/json

{
    "title": "Go to the city!!"
}

### Complete task
POST {{Host}}/tasks/77349935-a972-4e84-ac99-446729979f24/complete