@Host=http://localhost:4002

### Create task
POST {{Host}}/tasks
Content-Type: application/json

{
    "title": "Wash the car"
}

### Complete task
POST {{Host}}/tasks/6a3fc519-f684-4546-a5a5-671257c3f2b0/complete